name: CansteinSupportUtils
version: '${project.version}'
main: me.cookieblaster.cansteinsupportutils.CansteinSupportUtils
api-version: '1.19'

commands:
  tpdeath:
    syntax: "/tpdeath <player>"
    description: "Dieser Command teleportiert den Sender zur letzten Todesposition des übergebenen Spielers und setzt den teleportierten in Gamemode Spectator."